src/Entity/Quiz.php
<?php
declare(strict_types=1);

namespace App\Entity;

use App\Repository\QuizRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuizRepository::class)
 */
class Quiz
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private string $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isActive;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTimeInterface $createDate;

    /**
     * @ORM\OneToMany(targetEntity=Result::class, mappedBy="quiz")
     */
    private Collection $results;

    /**
     * @ORM\ManyToMany(targetEntity=Question::class, fetch="EAGER")
     */
    private Collection $questions;

    public function __construct()
    {
        $this->results = new ArrayCollection();
        $this->questions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIsActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getCreateDate(): DateTimeInterface
    {
        return $this->createDate;
    }

    public function setCreateDate(DateTimeInterface $createDate): self
    {
        $this->createDate = $createDate;

        return $this;
    }

    /**
     * @return Collection|Result[]
     */
    public function getResults(): Collection
    {
        return $this->results;
    }

    public function addResult(Result $result): self
    {
        if (!$this->results->contains($result)) {
            $this->results[] = $result;
            $result->setQuiz($this);
        }

        return $this;
    }

    public function removeResult(Result $result): self
    {
        if ($this->results->contains($result)) {
            $this->results->removeElement($result);
            if ($result->getQuiz() === $this) {
                $result->setQuiz(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->contains($question)) {
            $this->questions->removeElement($question);
        }

        return $this;
    }
}

src/Entity/Result.php
<?php
declare(strict_types=1);

namespace App\Entity;

use App\Repository\ResultRepository;
use DateInterval;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ResultRepository::class)
 */
class Result
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="results", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private User $user;

    /**
     * @ORM\ManyToOne(targetEntity=Quiz::class, inversedBy="results", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private Quiz $quiz;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTimeInterface $startDate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTimeInterface $endDate = null;

    /**
     * @ORM\Column(type="decimal", precision=4, scale=2, nullable=true)
     */
    private float $result;

    /**
     * @ORM\OneToMany(targetEntity=Progress::class, mappedBy="result", fetch="EAGER")
     */
    private Collection $progress;

    public function __construct()
    {
        $this->progress = new ArrayCollection();
        $this->result=0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getQuiz(): Quiz
    {
        return $this->quiz;
    }

    public function setQuiz(Quiz $quiz): self
    {
        $this->quiz = $quiz;

        return $this;
    }

    public function getStartDate(): DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(?DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getDuration(): ?DateInterval
    {
        if ($this->endDate) {
            return $this->endDate->diff($this->startDate);
        }

        return null;
    }

    public function getResult(): ?float
    {
        return $this->result;
    }

    public function setResult(float $result): self
    {
        $this->result = $result;

        return $this;
    }

    /**
     * @return Collection|Progress[]
     */
    public function getProgress(): Collection
    {
        return $this->progress;
    }

    public function addProgress(Progress $progress): self
    {
        if (!$this->progress->contains($progress)) {
            $this->progress[] = $progress;
            $progress->setResult($this);
        }

        return $this;
    }

    public function removeProgress(Progress $progress): self
    {
        if ($this->progress->contains($progress)) {
            $this->progress->removeElement($progress);
            if ($progress->getResult() === $this) {
                $progress->setResult(null);
            }
        }

        return $this;
    }
}

src/Controller/QuizController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use App\Entity\Answer;
use App\Entity\Quiz;
use App\Entity\User;
use App\Form\QuizProcessFormType;
use App\Service\QuizService;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class QuizController
 * @IsGranted("ROLE_USER")
 */
class QuizController extends AbstractController
{
    private QuizService $service;
    private EntityManagerInterface $em;

    /**
     * QuizController constructor.
     * @param QuizService $service
     * @param EntityManagerInterface $em
     */
    public function __construct(QuizService $service, EntityManagerInterface $em)
    {
        $this->service = $service;
        $this->em = $em;
    }

    /**
     * @Route("/quizes", name="app_quizes")
     * @param Request $request
     * @return Response
     * @throws NonUniqueResultException
     */
    public function onQuizzesPage(Request $request): Response
    {
        $page = $request->query->getInt('page', 1);
        $searchCriteria = $request->query->get('search');

        $pagination = $this->service->getPaginationQuizzes($page, $searchCriteria);
        $leaders = $this->service->getLeadersForPage($pagination);

        return $this->render
        (
            'quiz/all_quizes.html.twig',
            ['pagination' => $pagination, 'leaders' => $leaders]
        );
    }

    /**
     * @Route ("/quiz_info/{id}", name="app_quiz_info")
     * @param Quiz $quiz
     * @return Response
     */
    public function quizInfo(Quiz $quiz): Response
    {
        /**@var User $user */
        $user = $this->getUser();
        $result = $this->service->getResult($user, $quiz);
        $topResults = $this->service->findTopLeaders($quiz);
        $rate = $result && $result->getEndDate() ? $this->service->findUserPlace($user, $quiz) : null;

        return $this->render('quiz/quiz_info.html.twig', [
            'quiz' => $quiz,
            'topResults' => $topResults,
            'result' => $result,
            'rate' => $rate,
        ]);
    }

    /**
     * @Route ("/quiz_info/{id}/leaders", name="app_quiz_leaders")
     * @param Quiz $quiz
     * @param Request $request
     * @return Response
     */
    public function leaderBoard(Quiz $quiz, Request $request)
    {
        $page = $request->query->getInt('page', 1);
        $pagination = $this->service->getPaginateLeaders($quiz, $page);

        return $this->render('quiz/leaderboard.html.twig', [
            'quiz' => $quiz,
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route ("/quiz/{id}", name="app_quiz")
     * @param Quiz $quiz
     * @param Request $request
     * @return Response
     */
    public function proceed(Quiz $quiz, Request $request): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $result = $this->service->startParticipate($quiz, $user);

        if (!($quiz->getIsActive()) || $result->getEndDate()) {
            return $this->redirectToRoute('app_quiz_info', ['id' => $quiz->getId()]);
        }

        foreach ($quiz->getQuestions() as $question) {
            if (!$this->service->isProceed($question, $result)) {
                $form = $this->createForm(QuizProcessFormType::class, null, ['question' => $question]);
                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {
                    /** @var Answer $answer */
                    $answer = ($form->getData())['answer'];
                    $this->service->createNewProgress($result, $answer);

                    $request->getSession()->set('question', $question->getName());
                    $request->getSession()->set('answer', $answer->getName());
                    $request->getSession()->set('isRight', $answer->getIsRight());
                    $request->getSession()->set('progress', $result->getProgress()->count());

                    return $this->redirectToRoute('app_show_answer', [
                        'id' => $quiz->getId(),
                    ]);
                }

                return $this->render('quiz/proceed.html.twig', [
                    'form' => $form->createView(),
                    'quiz' => $quiz,
                    'result' => $result,
                    'question' => $question]);
            }
        }
        $result->setEndDate(new DateTime());
        $this->em->persist($result);
        $this->em->flush();

        return $this->redirectToRoute('app_quiz_info', ['id' => $quiz->getId()]);
    }

    /**
     * @Route ("/quiz/{id}/answer", name = "app_show_answer")
     * @param Quiz $quiz
     * @param Request $request
     * @return Response
     */
    public function showAnswer(Quiz $quiz, Request $request): Response
    {
        $session = $request->getSession();
        $question = $session->remove('question');
        $answer = $session->remove('answer');
        $progress = $session->remove('progress');
        $isRight = $session->remove('isRight');
        if (!$question || !$answer || $isRight === null) {
            return $this->redirectToRoute('app_quiz', ['id' => $quiz->getId()]);
        }

        return $this->render('quiz/proceed_answer.html.twig', [
            'question' => $question,
            'quiz' => $quiz,
            'answer' => $answer,
            'isRight' => $isRight,
            'progress' => $progress
        ]);
    }
}

templates/quiz/all_quizes.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'quiz.es'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('quizes_page') }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="tbl">
            <div class="d-flex justify-content-center">
                <h3>{{ 'quiz.count'|trans }}: {{ pagination.getTotalItemCount }}</h3>
                <form class="form-inline" action="{{ url('app_quizes') }}">
                    <input class="form-control mr-sm-2" type="search" placeholder="{{ 'quiz.search'|trans }}"
                           aria-label="Search" name="search">
                    <button class="btn btn-outline-success my-2 my-sm-0"
                            type="submit">{{ 'quiz.search.button'|trans }}</button>
                </form>
            </div>

            <table class=" table-q">
                <thead>
                <tr>
                    <th{% if pagination.isSorted('q.name') %} class="sorted"{% endif %}>
                        {{ knp_pagination_sortable(pagination, 'quiz.name'|trans,'q.name') }}
                    </th>

                    <th{% if pagination.isSorted('q.isActive') %} class="sorted"{% endif %}>
                        {{ knp_pagination_sortable(pagination,  'quiz.status'|trans,'q.isActive') }}
                    </th>

                    <th{% if pagination.isSorted('q.createDate') %} class="sorted"{% endif %}>
                        {{ knp_pagination_sortable(pagination,  'quiz.date.create'|trans,'q.createDate') }}
                    </th>
                    <th> {{ 'quiz.leader'|trans }}</th>

                    <th>
                        {{ 'quiz.participants'| trans }}
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for quiz in pagination %}
                    <tr>
                        <th><a href="{{ url('app_quiz_info',{id:quiz.id}) }}">{{ quiz.name }}</a></th>
                        <th{% if not  quiz.isActive %} style="color: #db7778" {% endif %}
                                {% if  quiz.isActive %} style="color: #3ac31a" {% endif %} >
                            {% if  quiz.isActive %}{{ 'quiz.active'|trans }}{% endif %}
                            {% if not  quiz.isActive %}{{ 'quiz.close'|trans }}{% endif %}
                        </th>
                        <th>{{ quiz.createDate.format('quiz.date.format'|trans) }}</th>
                        <th>
                            {% if  attribute(leaders, quiz.id).user.name is defined %}
                                {{ attribute(leaders, quiz.id).user.name }}
                            {% else %}
                                {{ 'quiz.people.no'|trans }}
                            {% endif %}

                        </th>
                        <th>{{ quiz.results | length }} {{ 'quiz.people'|trans }}</th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="d-flex justify-content-center meh">
                {{ knp_pagination_render(pagination) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/quiz/leaderboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'lb.title'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('quizes_page') }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="tbl">
            <div class="d-flex justify-content-center">
                <h3>{{ 'lb.count' |trans }}: {{ pagination.getTotalItemCount }}</h3>
            </div>
            <table class=" table-q">
                <thead>
                <tr>
                    <th>{{ 'lb.number' |trans }}</th>
                    <th>{{ 'lb.name' |trans }}</th>
                    <th>{{ 'lb.score' |trans }}</th>
                    <th>{{ 'lb.duration' |trans }}</th>
                </tr>
                </thead>
                <tbody>
                {% for result in pagination %}
                    <tr>
                        <th>{{ loop.index }}</th>
                        <th><a>{{ result.user.name }}</a></th>
                        <th>{{ result.result }}</th>
                        <th>{{ result.duration.format("%dd:%hh:%im:%ss") }}</th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="d-flex justify-content-center meh">
                {{ knp_pagination_render(pagination) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/quiz/proceed.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ quiz.name }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('quiz') }}
{% endblock %}

{% block body %}
    <div class="box">
        {{ 'qp.question'|trans }} №{{ (result.progress|length+1) }} {{ 'qp.of'|trans }} {{ quiz.questions|length }}<br>
        <div class="question">{{ question.name }}</div>
        {{ form_start(form) }}
        <div class="answers">
            {{ form_widget(form) }}
        </div>
        <button type="submit" id="btn"> {{ 'qp.answer'|trans }}</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/quiz/proceed_answer.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ quiz.name }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('quiz') }}
{% endblock %}

{% block body %}
    <div class="box">
        {{ 'qp.question'|trans }} №{{ progress }} {{ 'qp.of'|trans }} {{ quiz.questions|length }}<br>
        <div class="question">{{ question }}</div>
        <p>answer: {{ answer }}</p>
        {% if isRight %}
            <div class="right">
                {{ 'qp.right'|trans }}
            </div>
        {% endif %}
        {% if not isRight %}
            <div class="wrong">{{ 'qp.wrong'|trans }}
            </div>
        {% endif %}

        <form action="{{ url('app_quiz', {id: quiz.id} ) }}">
            <button type="submit">  {{ 'qp.next'|trans }}</button>
        </form>
    </div>
{% endblock %}

templates/quiz/quiz_info.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ quiz.name }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('quiz_info') }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="d-flex justify-content-center">
            <h2>{{ quiz.name }}</h2>
        </div>

        <div class="row flex-fill">
            {# QUIZ INFO #}
            <div class="col-sm quiz-i">
                <div class="d-flex justify-content-center">
                    <h3>{{ 'qi.title'|trans }}</h3>
                </div>
                <table>
                    <tr>
                        <th>{{ 'qi.created'|trans }}:</th>
                        <th>{{ quiz.createDate.format( 'quiz.date.format'|trans ) }}</th>
                    </tr>
                    <tr>
                        <th>{{ 'qi.status'|trans }}:</th>
                        <th{% if not  quiz.isActive %} class="wrong" {% endif %}
                                {% if  quiz.isActive %} class="right" {% endif %} >
                            {% if  quiz.isActive %}{{ 'quiz.active'|trans }}{% endif %}
                            {% if not  quiz.isActive %}{{ 'quiz.close'|trans }}{% endif %}</th>
                    </tr>
                    <tr>
                        <th>{{ 'qi.count.questions'|trans }}:</th>
                        <th>{{ quiz.questions.count }}</th>
                    </tr>
                    <tr>
                        <th>{{ 'qi.count.participants'|trans }}:</th>
                        <th>{{ quiz.results.count }}</th>
                    </tr>
                </table>
            </div>

            {# LEADERS #}
            <div class="col-sm quiz-i">
                <table>
                    <thead>
                    <tr>
                        <th colspan="4">
                            <h3>
                                <a href="{{ url('app_quiz_leaders', {id:quiz.id}) }}"> {{ 'qi.leaders'|trans }}</a>
                            </h3>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th>{{ 'qi.place'|trans }}</th>
                        <th>{{ 'qi.name'|trans }}</th>
                        <th>{{ 'qi.result'|trans }}</th>
                        <th>{{ 'qi.time'|trans }}</th>
                    </tr>
                    {% for tr in topResults %}
                        <tr>
                            <th>{{ loop.index }}</th>
                            <th>{{ tr.user.name }}</th>
                            <th>{{ tr.result }}</th>
                            <th>{{ tr.duration.format("%dd:%hh:%im:%ss") }}</th>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        {# RESULT WITH START BUTTON #}
        <div class="row flex-fill">
            <div class="col-sm">
                <div class="rez">
                    <div class="d-flex justify-content-center">
                        <h3>{{ 'qi.progress'|trans }}:</h3>
                    </div>
                    <p>{{ 'qi.status'|trans }}:
                        {% if result is null %}{{ 'qi.status.no'|trans }}{% endif %}
                        {% if result is not null %}
                        {% if result.endDate is null %}{{ 'qi.status.in'|trans }}{% endif %}
                        {% if result.endDate is not null %}{{ 'qi.status.off'|trans }}
                    </p>
                    <p>{{ 'qi.result'|trans }}: {{ result.result }}
                        {% endif %}
                        {% endif %}
                    </p>
                    {% if rate %}
                        <p>
                            {{ 'qi.rate'|trans }}: {{ rate }}
                        </p>
                    {% endif %}
                    <div class="d-flex justify-content-center">
                        <form action="{{ url('app_quiz',{id:quiz.id}) }}">
                            <button type="submit"
                                    {% if result is null and quiz.isActive %}>{{ 'qi.button.start'|trans }}{% endif %}
                                {% if not quiz.isActive or result and result.endDate %} hidden>{% endif %}
                                {% if result is not null and result.endDate is null and quiz.isActive %} >{{ 'qi.button.continue'|trans }}{% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        {# ANSWERS #}
        {% if result and (result.progress|length) > 0 %}
            <div class="row flex-fill tac">
                <div class="col-sm">
                    <div class="d-flex justify-content-center">
                        <h3>{{ 'qi.answers'|trans }}:</h3>
                    </div>
                    <table>
                        <thead>
                        <tr>
                            {% for question in quiz.questions %}
                                <th>{{ (loop.index) }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            {% for progress in result.progress %}
                                <th {% if progress.isRight %} class="ans-t">✓{% endif %}
                                    {% if not progress.isRight %} class = "ans-f">×{% endif %}
                                </th>
                            {% endfor %}
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}